// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"google.golang.org/grpc"
	"neo4j/internal/dao"
	grpc2 "neo4j/internal/server/grpc"
	"neo4j/internal/service"
	"neo4j/pkg/conf"
)

// Injectors from wire.go:

func InitApp() (*grpc.Server, func(), error) {
	string2 := conf.ConfigFile()
	configs, err := conf.New(string2)
	if err != nil {
		return nil, nil, err
	}
	db, err := dao.New(configs)
	if err != nil {
		return nil, nil, err
	}
	serviceService := service.New(db)
	server := grpc2.New(serviceService)
	return server, func() {
	}, nil
}
